### ISSUE TITLE
multiple issues on various systems

### ISSUE THREAD

**Issue by gieses** [hnolCol/instantclue#11]
Thanks for developing InstantClue! We are using InstantClue in our undergrad teaching for the analysis of mass spec data ~ roughly 70 people.

We had several issues for which I unfortunately cannot give many details. I am aware that this is a difficult situation for you but I hope it is beneficial for you:

- mac/windows plotting not working; on mac the error that shows is something along the lines "object ScatterPointSize not found"
- [saving sessions](https://github.com/hnolCol/instantclue/issues/5#issue-397567614) 
- working with columns after renaming sometimes not possible, error message seems to indicate that the underlying dataframe was not changed ("column name not in index"). The console shows the new name of the column as well as the interface
- on a mac reading of excel files did not work "package xlrd not found"
- minor: many people were confused that the default separator for CSV files is ";" (dunno if it is system specific US/GER?)

HTH
-Sven

**Comment by hnolCol** [comment]
Hi Sven, 

very cool to hear that you are using Instant Clue for teaching purposes of mass spec data! 
I will respond to the reported issues below:

1. It's a bug and happens when you are using the "+" sign instead of the "arrow up" button to load your first data frame. Fixed in the source code and in the next binary release.
2. Still persists, working on it.
3. We have fixed this.
4. Solved.
5. It's "sadly" the default in GER when exporting from excel. 

Sorry for the inconvenience within your course but the new version will fix most likely all of the reported issues. I will close the issue upon release of the new version.
Best wishes from Cologne

Hendrik

**Comment by gieses** [comment]
Hi Hendrik,

awesome. Thanks for your swift response! Looking forward to the next version.

best wishes,
Sven

**Comment by cforbrig** [comment]
Hi Hendrik,
Any news on that? 
We'll have the course again next week. Is there a new version to try out?
Best wishes,
Christian

**Comment by hnolCol** [comment]
Hi Christian, 

we actually have decided to reconstruct InstantClue in a more modern framework (PyQt5), hence there was no recent update.

I will upload today a beta version that might miss some functions of the old version and has very limited documentation but includes very useful new features. I will try to make a video for the newest widgets and functions. 

If there are critical functions missing in this version that you require for your course, I will give them highest priority and incorporate them asap before next week. 

All the issues are addressed in the new version. (saving the session does however not save the current graph, but only the data and the main figures). 

Hope that is fine with you.  For urgent requests, you can contact me directly: h.nolte@age.mpg.de

Best wishes

Hendrik

**Comment by cforbrig** [comment]
Hi Hendrik,
that sounds great, thank you! Looking forward to the beta version and the video.
Best wishes,
Christian

Von: hnolCol [mailto:notifications@github.com]
Gesendet: Dienstag, 16. Februar 2021 10:20
An: hnolCol/instantclue <instantclue@noreply.github.com>
Cc: Forbrig, Christian <c.forbrig@tu-berlin.de>; Comment <comment@noreply.github.com>
Betreff: Re: [hnolCol/instantclue] multiple issues on various systems (#11)


Hi Christian,

we actually have decided to reconstruct InstantClue in a more modern framework (PyQt5), hence there was no recent update.

I will upload today a beta version that might miss some functions of the old version and has very limited documentation but includes very useful new features. I will try to make a video for the newest widgets and functions.

If there are critical functions missing in this version that you require for your course, I will give them highest priority and incorporate them asap before next week.

All the issues are addressed in the new version. (saving the session does however not save the current graph, but only the data and the main figures).

Hope that is fine with you. For urgent requests, you can contact me directly: h.nolte@age.mpg.de<mailto:h.nolte@age.mpg.de>

Best wishes

Hendrik

**Comment by hnolCol** [comment]
Hi Chrstian

new version dev-snap shot released.

Fixes all issues even though saving the session is still limited.

File Loading Settings can be now altered using the Settings Dialog. These settings will be saved and restored. 
The reading properties are also applied when you copy and paste data from your clipboard (Excel) into InstantClue.

![FileSettings](https://user-images.githubusercontent.com/24191910/108192662-d57dad00-7114-11eb-84eb-dd99477ec554.png)

I am closing this issue now. 
Please report any bug (as it is the first release of the new version I expect several). Thank you very much for your help.

Best wishes

Hendrik
