### ISSUE TITLE
Error when trying to import data on MacOS -  all data imported as categorical

### ISSUE THREAD

**Issue by roberthardt** [hnolCol/instantclue#16]
Dear developers,

for some strange reason I cannot get data into Instant Clue on my Mac using the latest development build. Regardless which data import option I use all my data columns are imported as categories even if they contain only numeric data. I also tried exporting to txt from Excel but got exactly the same result. Maybe I am to stupid, but i also tried switching the decimal and thousand separator, but I did not help.

Hope you can help me.

Best

Robert

**Comment by roberthardt** [comment]
Fixed it. Seemed to be an issue with the xlsx files. Got them from a collaborator, which exported them from R. After opening and saving them on my Mac I can import them into InstantClue.

Best

Robert

**Comment by hnolCol** [comment]
Hi Robert,

it is indeed an "issue" with Excel, most commonly columns contain the "#VALUE!" error which are not recognised as NaN but rather as a string. I will take care of the VALUE error but it is only valid if English is set as the preferred language. 
Please let me know in the discussion section if you are missing some features that should be included in InstantClue :) 

Best wishes

Hendrik
