### ISSUE TITLE
Download issue

### ISSUE THREAD

**Issue by peterfaull** [hnolCol/instantclue#17]
Hello.
When I click on the Windows icon for download, no download begins.
This happens in both Chrome and Firefox.
The icon color changes from blue to brown but nothing further.

Any assistance would be appreciated.

Best,
Peter

**Comment by hnolCol** [comment]
Hi Peter, 
you actually have to choose below a release type (stable, development, development build or development snapshot) and click on it. At the moment only the latter exists. 
<img width="570" alt="image" src="https://user-images.githubusercontent.com/24191910/111385766-8f801e80-86ab-11eb-946f-2856a75cc9aa.png">
Nevertheless, you are completely right that clicking on the os icon should redirect to a download page. Therefore, from now on clicking on the item links to the GitHub [release page](https://github.com/hnolCol/instantclue/releases) from which you can download the latest InstantClue version.  

I am closing the issue.
