### ISSUE TITLE
poor performance

### ISSUE THREAD

**Issue by prvst** [hnolCol/instantclue#2]
I found your project very interesting but I had no success in using it on a not-so-large data set (protein matrix, 500 obs. 90 variables). I can upload the file but it freezes after I drag values to the top bars, it looks like that the processing happens on a single core, so even by having a high speed computer would not solve this issue. Is there a way to improve the program performance ?I have an even larger data set that I wish to analyze. 

Thanks

**Comment by hnolCol** [comment]
Your data matrix looks rather small and it should work. 
Could you send me an email to h.nolte@uni-koeln.de to explain what you have been trying to do with some fake data simulating your original data set attached? Of course sending me the original with "hiding" the biological meaning would also work. 

We are working on multi-processing at the moment but it is not yet ready for all platforms.
