### ISSUE TITLE
Can't install instantclue in Mac

### ISSUE THREAD

**Issue by DKsamy** [hnolCol/instantclue#23]
Hi,

I tried to install instantclue in mac but it is not possible even when I allow to install unverified source. I use latest OS Big Sur. Kindly help me with this problem.

**Comment by hnolCol** [comment]
Hi, 

could you please go to InstantClue -> RightClick -> Show Package Content -> MacOS -> find the executable "instantly" and double click. A console will open which hopefully shows an useful error. 

I know that there were some problems with OS BigSur and PyQt5 which is used by InstantClue, but also believed that with PyQt 15.5.2, the issues were eliminated. Please let me know and thank you!

**Comment by hnolCol** [comment]
I am closing this issue, hope it all works now. Otherwise please open another one.
