### ISSUE TITLE
Subtract by median unexpected behaviour

### ISSUE THREAD

**Issue by pdcharles** [hnolCol/instantclue#3]
The behaviour of the operation 'Row & column calculations -> Basic -> Substract by... -> Column Median' produces unexpected results on the Mac release of v0.4.9.

Reproduction:
Using the "fixed acidity" column from "winequality-white.csv" perform two sets of operations (all within 'Row & column calculations -> Basic'
A (divide-then-log):
     1. 'Divide by... -> Column Median'
     2. 'Logarithmic -> log2'
B (log-then-subtract):
     1. 'Logarithmic -> log2'
     2. 'Substract by... -> Column Median' operation

Expected outcome: the results of A and B should be identical.  The medians of A and B should be 0.
Observed outcome:  B = A - ~4.03

Scatter plot:
![image](https://user-images.githubusercontent.com/12846789/47151813-b1a2c600-d2d2-11e8-8c74-6d72d291f95b.png)

When I perform the the log-then-subtract sequence but instead manually input the median value (obtained from 'Summary Statistics -> 50%') by using 'Substract by... -> Value' rather than 'Substract by... -> Column Median', then the result is identical to A.

It looks like you might have a bug in analyze_data.py:1164 - you do not subset the list of median values before zipping with selectedColumns, so it will always pair the first value from selectedColumns with the median of the first column in the entire data frame.

P.S. 'Substract' is (typically considered) a typo, with the correct spelling being 'Subtract'.

**Comment by hnolCol** [comment]
Thank you very much for your feedback and pull request, absolutely right. Typo is correct as well.
