### ISSUE TITLE
file loading error

### ISSUE THREAD

**Issue by llalmall** [hnolCol/instantclue#40]
I am using the latest version on win, error message pops up once I load the .xlsx file.
When I used the old version, it didn't happen..

**Comment by hnolCol** [comment]
Dear llalmall, 

thanks for opening this issue. It is quite hard to diagnose the problem without knowing having the size. 
Could you please send me file to h.nolte@age.mpg.de 

Easiest is to export to tab delimited txt file or to use copy & paste from excel into InstantClue. Just copy the data and go to InstantClue and press Ctrl-v/Cmd-v.  Please check the [Wiki page](https://github.com/hnolCol/instantclue/wiki/Load-files) for detail description of the parameters in txt files. I hope it helps. I am going to implement a more interactive excel importer in the next release. 

Best wishes

Hendrik

**Comment by hnolCol** [comment]
This is actually a bug due to a missing dependency in the compiled windows version. Thank you @llalmall. It will be fixed in the new release. Likely coming this week online with an extended setting and preview for excel files. 
I hope the copy paste solution works for you at the moment. 
I will close the issue with this.

**Comment by llalmall** [comment]
Thank you! :)

> 2/9/22 오전 1:19, hnolCol ***@***.***> 작성:
> 
> This is actually a bug due to a missing dependency in the compiled windows version. Thank you @llalmall <https://github.com/llalmall>. It will be fixed in the new release. Likely coming this week online with an extended setting and preview for excel files.
> I hope the copy paste solution works for you at the moment.
> I will close the issue with this.
> 
>
