### ISSUE TITLE
Groupings in clustering

### ISSUE THREAD

**Issue by szabzola** [hnolCol/instantclue#42]
Hi,
thanks for this great app.
In v0.11.0 for on Windows 10, if I have Groups defined, and hclust.display.gouping is True, no clustering occurs (no heatmap just blank figure). If there are no groups defined, or hclust.display.gouping is set to False it works. Tested on 2 PCs with 2 different dataframes.
(by the way, for grouping: I do find the "Group by split string" option).
Best regards,
Zoltan

**Comment by hnolCol** [comment]
Hi Zoltan, thanks for helping to improve the software. Thanks for the bug report. It is corrected with the last pr to 0.11.1 and will be in the compiled 0.11.1 which I will upload later today (hopefully).
Di you mean to say that you cannot find the "Group by split string" option? :) 
If so, in the dialog for "annotate groupings" you can select the column names that should be used to identify the grouping and then open it using the context menu. 

In general, I feel that a preview of the first column would be useful in such the dialog what do you think? 

<img width="603" alt="image" src="https://user-images.githubusercontent.com/24191910/153584874-97c50f71-b3c6-4a58-8e51-6eb14c56fbba.png">

**Comment by szabzola** [comment]
Dear Hendrik,
Thanks for the quick response on bug, looking forward to new version.
Thanks for the hint for grouping by split, now I can use it (I have tried right click everywhere, except for that :-))
Yes, a preview would be really useful for finding the right settings.
Best regards,
Zoltan

**Comment by hnolCol** [comment]
I have added the preview label function. Please let me know in the [Discussions](https://github.com/hnolCol/instantclue/discussions) if features are missing that you would like use. You can also email me h.nolte@age.mpg.de 

<img width="599" alt="image" src="https://user-images.githubusercontent.com/24191910/153598155-6f0bd5a4-358c-4474-a468-4369bddea41f.png">

Thanks for reporting the bug. I am closing it now as it was a specific bug that could be resolved and should work now.

**Comment by szabzola** [comment]
Thanks. I will try it, once it is released.

**Comment by szabzola** [comment]
Thanks it works fine.
However if I also add category colors to heatmap, the Titles of groups rows and color column overlap, can I set somehow position or text of those? (by the way, it would be nice, if more than one color category could be added).

**Comment by hnolCol** [comment]
Good to hear. :) I opened a [discussion](https://github.com/hnolCol/instantclue/discussions/46) for enhancements of the hierarchical clustering to make it more visible. Please add any ideas/enhancements regarding the clustering there. 
Sadly you will probably end up refining the figure for publication in a vector graphic software such as adobe illustrator or coreldraw after exporting it to a pdf/svg file. Thanks for your contribution, highly appreciate.
