### ISSUE TITLE
Saving session error

### ISSUE THREAD

**Issue by daniswan** [hnolCol/instantclue#5]
When trying to save a session I get the following error:
Session not saved.
Error Can't pickle < class
'matplotlib.backends._backend_agg.BufferRegion'>:attribute
lookup BufferRegion on matplotlib.backends._backend_agg
failed

**Comment by hnolCol** [comment]
Thank you for your comment. The soonish upcoming 0.5.4 has expereinced a great update in saving that should improve. However, if you can recall, could you please let me know which kind of plot you have used?

**Comment by daniswan** [comment]
I think it was a scatter plot.

Danielle

**Comment by leonfrcom** [comment]
I get the same error when trying to save a scatter blot session. I use Anaconda python, could this lead to the error?

**Comment by hnolCol** [comment]
Thanks @szabzola. This issue is fixed withe init commit to 0.11.2 and occurred due to request of a parameter (hasTooltip) which did only exist when a tooltip was added. Thank you!

I will close this issue please, open a new one if there is an error regarding the saving.
