### ISSUE TITLE
Boxplot scrambled after axis setting

### ISSUE THREAD

**Issue by szabzola** [hnolCol/instantclue#56]
Hi,
After applying axis setting (axis title) median line and mean dots are scrambled on some boxplots (eg. green box median, and mean dot on yellow too).
Attached image: before (left) and after (right) axis setting.
![image](https://user-images.githubusercontent.com/61981001/160851663-99a9329c-1142-48c5-b168-7f5288172780.png)

Best regards,
Zoltan

**Comment by hnolCol** [comment]
Interesting yet confusing bug. I will look into it. Is it always happening or only if you execute changes in an explicit order?

**Comment by szabzola** [comment]
I have noticed, that it only occurs, if boxplot.showfliers=TRUE.
I hope it helps.
Regards,

**Comment by szabzola** [comment]
I have noticed, that it only occurs, if boxplot.showfliers=TRUE.
I hope it helps.
Regards,

**Comment by szabzola** [comment]
Or if boxplot.showmeans=TRUE than mean markers are scrambled (even if fliers is FALSE)...

**Comment by szabzola** [comment]
Hi, thanks for release v0.11.2. This bug (scrambling markers after axis settings) still exists in this release and applies to the new boxenplot too.
Tip: boxenplot.showmeans could be also useful. By the way violin.show.means shows median I think.
Regards,

**Comment by hnolCol** [comment]
Hi, yeah I am sorry to have adressed this issue. I will now focus on it. I will add the boxenplot.showmeans and double check the violin parameter.

**Comment by hnolCol** [comment]
Updating matplotlib to 3.6 on windows resolved the issue. if you want me to send you a snap shot, please contact me via mail. I will include the fix in the next release (if you cannot wait, write me an email h.nolte@age.mpg.de for a dev snapshot :) ). 

I am closing the issue. If it still exists in your case, I will reopen.
