### ISSUE TITLE
Drag and Drop Issue

### ISSUE THREAD

**Issue by enonimos** [hnolCol/instantclue#6]
Hello, I am using the latest InstantClue 0.5.2 and have followed the advice on the website to make sure that the OS scaling effects are at 100%, but I still cannot drag and drop numerical or category factors into the receiver box.  Also, I have tried to run the program using increased compatibility settings and with admin rights. I have also re-downloaded the software and tried different locations and hard drives on my computer.  In the end, the result is the same.

A colleague has tried InstantClue with the same data matrix and is able to perform drag and drop functions.

Is there any else I can try?

Thanks in advance for your assistance.
Todd

**Comment by hnolCol** [comment]
Hi Todd, 
which windows paltform are you using?

**Comment by enonimos** [comment]
Hi, the issue was fixed for me in your new 0.5.3 version.

For your reference, I was using windows 10,but again, the issue is resolved
with new version. Thanks.

**Comment by hnolCol** [comment]
Ok, closing the issue. Thanks for your report
