### ISSUE TITLE
Filtering Integers

### ISSUE THREAD

**Issue by marinovaiva** [hnolCol/instantclue#62]
Selecting Numeric Floats entries and dragging them to the Filter button creates a Numeric Filter.

Is there a similar function for Integers?

The data I analyze is inconsistently exported as either floats or integers. Of course, I can convert the integers into floats before using IC, but this seems like a useful feature to have.

Thank you!

**Comment by hnolCol** [comment]
Thank you for the valid suggestion. In the upcoming release the user will be asked if the integer column should be considered as a continuous metric (eg as a numeric float) or a categorical value (such as "on" -1 and "off" - 0) for filtering. I will close the issue once it is published. 

Thank you! Btw you can also use the **discussions** section to suggest new features.

**Comment by hnolCol** [comment]
The current release #67 takes care of integer filtering. Let me know if you experience some problems. I am closing this issue.  Thanks for the feature request.
