### ISSUE TITLE
Exporting vector graphics error in v0.11.3

### ISSUE THREAD

**Issue by szabzola** [hnolCol/instantclue#68]
Hi,
thanks for the work on improvements.
In the new version I can export figure (or main figure) only in bitmnap formats, all vector graphics format gives similar error message:
"No module named 'matplotlib.backends.backend_svg'  "
This is messge with svg, the end is different with other formats (e.g. eps).
Best regards,
Zoltan

**Comment by hnolCol** [comment]
Hi Zoltan, 
uh okay. Does pdf work for you? Which is also a vector graphic? Thanks!

**Comment by szabzola** [comment]
Hi, yes pdf works.

**Comment by szabzola** [comment]
It works in v0.12.0.
Thanks
