### ISSUE TITLE
Categorical labeling not working

### ISSUE THREAD

**Issue by joeldf** [hnolCol/instantclue#7]
Hello,

I am attempting to annotate a volcano plot using a set of gene with a "+" denoting significance as was done in the example video.  When I try to do this, it does not work and I get the following error in the command prompt box that is running in the background: UnboundLocalError: local variable 'selectionLabels' referenced before assignment 

Occasionally when trying this the program will simply crash.  I am running this on a windows 7 environment and elevating to administrator did not solve the issue.

Please let me know if there is anything else I can try or info I can provide.

Joel

**Comment by joeldf** [comment]
I can also confirm that a previous version (downloaded in August) does work for annotating volcano plots as described above, so this appears to be an issue with 0.5.2.

**Comment by hnolCol** [comment]
Hi Joel, 
thank you for your comment, and late reply. This issue should be fixed in 0.5.3.
