### ISSUE TITLE
Cannot open on Mac 13.4

### ISSUE THREAD

**Issue by guddi9** [hnolCol/instantclue#71]
This is the first time I am trying to use Instantclue, so I am not sure if this is a problem that is limited to MacOS 13.4. But when I download the DMG and copy it to the programs folder, following error massage appears, when I try to run the program:

„InstantClue“ ist beschädigt und kann nicht geöffnet werden. Es empfiehlt sich, das Objekt in den Papierkorb zu bewegen.

This also happens when I go to the package content - MacOS - InstantClue

Do you have any idea how to solve this problem?

Thanks!

**Comment by hnolCol** [comment]
Please excuse the late reply. The problem occurred due to some problem in the app notarization. 

We have now fixed it. And the error message should disappear.  I uploaded the new dmg file and would be great to get some feedback if it works for you

cheers

**Comment by SebastianKallabis** [comment]
I am using MacOS 13.4 and it works 👍

**Comment by guddi9** [comment]
works for me, too. thanks!!
