### ISSUE TITLE
Feature request - commandline - load file

### ISSUE THREAD

**Issue by lareooreal** [hnolCol/instantclue#9]
Hi developers!
Love the current state.
Is it possible to parse the commandline with a minimum of functionality, please?
I would like to launch the program and hand over the path to a ASCII/Excel file to open.
This way I can integrate the program in all my workflows.

Thanks!!!!!

Lareooreal

**Comment by hnolCol** [comment]
Hi Lareooreal, 

good idea. Will implement that. Hopefully already for the next release. Closing the request.
